apiVersion: v1
kind: Service

metadata:
  name: mysql-service

spec:
  type: ClusterIP
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
#      nodePort: 30002
      port: 3306ㅌ
      targetPort: 3306
